### ISSUE TITLE
Cross-origin view transitions

### ISSUE THREAD

**Issue by noamr** [w3c/tpac2024-breakouts#48]
### Session description

Cross-document view transitions were built with same-origin navigations in mind, as a lot of information is shared between documents in order to perform the full set of same-document view transitions. 

In this session, we'll explore trade-offs that would let us grab *some* of the expressiveness of the existing view transitions, and enable that kind of smooth experience for cross-origin navigations, while keeping the security challenges in check.

### Session goal

Introduce and explore cross-origin view transitions, proposal and alternatives

### Who can attend

Anyone may attend (Default)

### IRC channel (Optional)

#css

### Other sessions where we should avoid scheduling conflicts (Optional)

#47, #57

**Comment by khushalsagar** [comment]
List of sessions to avoid a conflict with:

- https://github.com/w3c/tpac2024-breakouts/issues/43
- https://github.com/w3c/tpac2024-breakouts/issues/47

**Comment by noamr** [comment]
Closing, merging this one with #47.
