### ISSUE TITLE
Ecma Beyond ECMAScript—Highlights from some of the other 53 Technical Committees

### ISSUE THREAD

**Issue by gesa** [w3c/tpac2024-breakouts#86]
### Session description

Ecma is a standards body responsible for far more than specifying JavaScript™. There are currently 15 technical committees, and historically 54 total. Some of these technical committees focus on hardware, acoustics, and even consumer safety. Others, though, include programming languages (Dart, C#, Eiffel) and a variety of software-related topics ranging from supply chain security to Office Open XML formats. In this breakout session, we’ll explore these together and dive a little deeper on whichever the attendees find most interesting.

### Session goal

Discuss and explore the potential relationship with Ecma work areas most relevant to W3C participants

### Who can attend

Anyone may attend (Default)

### IRC channel (Optional)

#ecma-highlights

### Links to calendar

- [2024-09-25, 08:30 - 09:30](https://www.w3.org/events/meetings/6bf05e2c-56cf-4137-b918-5985080a54ed/)

**Comment by ianbjacobs** [comment]
Closed by @gesa and hopes it will happen next year.
